version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/auth-service"
    schedule:
      interval: "weekly"
    target-branch: "dev"

  - package-ecosystem: "maven"
    directory: "/tiny-img-service"
    schedule:
      interval: "weekly"
    target-branch: "dev"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
