services:
  tiny-img-nginx:
    image: nginx:1.27.0-alpine
    container_name: tiny-img-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tiny-img-auth-service
