global:
  scrape_interval: 30s
scrape_configs:
  - job_name: 'metrics'
    metrics_path: /q/metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['auth-service:8080', 'tiny-img-service:8080','notification-service:8080','ffmpeg-service:8080']