name: Auth Service - SonarQube Analysis

on:
  push:
    paths:
      - 'auth-service/**'
    branches:
      - main
      - dev
      - uat
      - qa
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    uses: ./.github/workflows/sonarqube-template.yml
    with:
      paths: ['auth-service/**']
      branches: ['main', 'dev', 'uat', 'qa']
      sonar-project-key: MateuxDotDev_tiny-img_AY_gwQ7jrsHxU9HD8Rkh
      sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
