name: Auth Service - Production

on:
  push:
    # paths:
    #   - 'auth-service/**'
    branches:
      - main

jobs:
  tag-and-push-prod-image:
    name: Tag and push the production image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./auth-service

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Maven project version
        run: |
          APP_VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Pull the uat image
        run: |
          docker pull mateuxlucax/tiny-img:auth-service-uat-${{ env.APP_VERSION }}

      - name: Tag the image with uat
        run: |
          docker tag mateuxlucax/tiny-img:auth-service-uat-${{ env.APP_VERSION }} mateuxlucax/tiny-img:auth-service-${{ env.APP_VERSION }}
          docker tag mateuxlucax/tiny-img:auth-service-uat-${{ env.APP_VERSION }} mateuxlucax/tiny-img:auth-service

      - name: Push the uat tags
        run: |
          docker push mateuxlucax/tiny-img:auth-service-${{ env.APP_VERSION }}
          docker push mateuxlucax/tiny-img:auth-service
