name: Auth Service - Build

on:
  push:
    # paths:
    #   - 'auth-service/**'
    branches:
      - dev

jobs:
  docker:
    name: Dockerize application
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./auth-service
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract Maven project version
        run: echo ::set-output name=version::$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mateuxlucax/tiny-img:auth-service-dev-${{ steps.project.outputs.version }}
