name: Tiny Img Service - Build

on:
  workflow_run:
    workflows: ["Tiny Img Service - SonarQube Analysis"]
    types:
      - completed
  push:
    paths:
      - 'tiny-img-service/**'
    branches:
      - dev

jobs:
  docker:
    name: Dockerize application
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./tiny-img-service
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Maven project version
        run: |
          APP_VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./tiny-img-service
          push: true
          tags: mateuxlucax/tiny-img:tiny-img-service-dev,mateuxlucax/tiny-img:tiny-img-service-dev-${{ env.APP_VERSION }}
